import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Users from './users'
import Link from 'next/link'
import All from './../components/all'
import Home2 from './../Home/home'


export default function Home() {
  
  return (

      <div className={styles.container}>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Home2></Home2>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
