import Head from 'next/head'
import Home2 from './../Home/home'


export default function Home() {
  
  return (

      <div>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Home2></Home2>
      </main>
    </div>
  )
}
